dist: trusty

addons:
  chrome: stable

language: node_js

node_js: "8"

sudo: false

install:
  - yarn install
  - yarn build
  - yarn build:readfeeds
  - yarn readfeeds

git:
  depth: 9999999

before_deploy:
  - rm -rf node_modules src src-feed-reader internal

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
  # on: master
  # username: azure_deployment_user       # If AZURE_WA_USERNAME isn't set
  # password: azure_deployment_password   # If AZURE_WA_PASSWORD isn't set
  # site: azure_deployment_sitename       # If AZURE_WA_SITE isn't set
  # slot: azure_deployment_slotname       # (optional) If AZURE_WA_SLOT isn't set
