dist: trusty

addons:
  chrome: stable

language: node_js

node_js: "8"

sudo: false

install:
  - yarn install
  - yarn build

# deploy:
#   local_dir: dist
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#   on:
#     branch: master

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
  # on: master
  # username: azure_deployment_user       # If AZURE_WA_USERNAME isn't set
  # password: azure_deployment_password   # If AZURE_WA_PASSWORD isn't set
  # site: azure_deployment_sitename       # If AZURE_WA_SITE isn't set
  # slot: azure_deployment_slotname       # (optional) If AZURE_WA_SLOT isn't set